name: Build
on: [push, pull_request]

jobs:
    shellcheck:
        runs-on: ubuntu-latest
        name: Shellcheck
        steps:
            - uses: actions/checkout@v2
            - name: Install shellcheck
              run: sudo apt-get update -qq && sudo apt-get install -y shellcheck
            - name: Check shell scripts
              run: bash shellcheck

    build_jessie:
        runs-on: ubuntu-latest
        name: Build Jessie (AMD64)
        needs: [ shellcheck ]
        steps:
            - uses: actions/checkout@v2
            - name: Fix for Ubuntu apt-daily.service triggering
              run: |
                while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
                    sleep 1
                done
            - name: Install requirements
              run: sudo make .installed-requirements
            - name: Build
              run: sudo bash buildone jessie amd64
            - name: Push
              if: github.ref == 'refs/heads/master'
              run: sudo bash pushone ${{ matrix.dist }} ${{ matrix.arch }}

    build:
        runs-on: ubuntu-latest
        needs: [ shellcheck ]
        strategy:
            matrix:
                dist: [stretch, buster]
                arch: [amd64, arm64]

        name: Build ${{ matrix.dist }} on ${{ matrix.arch }}
        steps:
            - uses: actions/checkout@v2
            - name: Fix for Ubuntu apt-daily.service triggering
              run: |
                while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
                    sleep 1
                done
            - name: Install QEMU static binfmt
              run: |
                sudo apt-get update -qq && \
                sudo apt-get install -y qemu-user-static
            - name: Install requirements
              run: sudo make .installed-requirements
            - name: Build
              run: sudo bash buildone ${{ matrix.dist }} ${{ matrix.arch }}
            - name: Build snapshot
              if: matrix.dist == 'buster' && github.ref == 'refs/heads/master'
              run: sudo bash buildone_snapshot ${{ matrix.dist }} "$(./snapshot_id)" ${{ matrix.arch }}
            - name: Tag latest
              if: matrix.dist == 'buster' && github.ref == 'refs/heads/master'
              run: sudo docker tag "alekitto/minideb:${{ matrix.dist }}-${{ matrix.arch }}" "alekitto/minideb:latest-${{ matrix.arch }}"
            - name: Push
              if: github.ref == 'refs/heads/master'
              run: sudo bash pushone ${{ matrix.dist }} ${{ matrix.arch }}
            - name: Push snapshot
              if: matrix.dist == 'buster' && github.ref == 'refs/heads/master'
              run: sudo bash pushone "buster-$(./snapshot_id)" ${{ matrix.arch }}
            - name: Push latest
              if: matrix.dist == 'buster' && github.ref == 'refs/heads/master'
              run: sudo bash pushone latest ${{ matrix.arch }}
